project:
  type: website
  output-dir: docs

website:
  title: "Louise E. Sinks"
  navbar:
    title: "Louise E. Sinks"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - href: blogroll.qmd
        text: "Blog Roll"
  google-analytics: "G-WR4VFC0MC2"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

